### ISSUE TITLE
[publish] dependencies not adjusted to use 'next' 

### ISSUE THREAD

**Issue by marcdumais-work** [theia-ide/theia-rust-extension#6]
Publishing a ```next``` version as part of CI, after a commit to master, now works. However the published module has ```@theia/*``` dependencies that use tag ```latest``` rather than ```next```. I think adjusting dependencies happens automagically for other repos we have, and does not require too much effort.

**Comment by dvc94ch** [comment]
When I wrote the plug-in I had problems with next releases. I think Sven opened a GitHub issue a couple of days later.
